version: '3.1'

services:
  app:
    build: ./app
    container_name: react_app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - main
  server:
    build: ./server
    container_name: json_server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    networks:
      -  main
networks:
  main: